import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["200", "400", "600", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} bg-primary-white antialiased`}>
        <Nav />
        {children}
        </body>
    </html>
  );
}
